# Generated by Django 3.1.7 on 2021-03-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.CharField(max_length=50)),
                ('porteur', models.CharField(max_length=100)),
                ('debut_op', models.DateField()),
                ('fin_op', models.DateField()),
                ('montant_CT', models.FloatField()),
                ('montant_UE', models.FloatField()),
                ('DP_CT_depot', models.FloatField()),
                ('DP_certif', models.FloatField()),
                ('statut_macro', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
