# Generated by Django 3.1.7 on 2021-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20210326_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='montant_public',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
