# Generated by Django 3.1.7 on 2021-03-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_enveloppe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_1',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_10',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_11',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_12',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_13',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_2',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_3',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_4',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_5',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_6',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_7',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_8',
        ),
        migrations.RemoveField(
            model_name='enveloppe',
            name='Axe_9',
        ),
    ]
