# Generated by Django 3.1.7 on 2021-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_auto_20210331_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_11',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_13',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_7',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Axe_9',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enveloppe',
            name='Enveloppe_totale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
