# Generated by Django 3.1.7 on 2021-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20210331_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_dépôt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
