# Generated by Django 3.1.7 on 2021-04-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0013_auto_20210413_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='indicateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type_indicateur', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('unité', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('valeur_prev', models.FloatField(blank=True, default=0, null=True)),
                ('valeur_conv', models.FloatField(blank=True, default=0, null=True)),
                ('valeur_real', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
