# Generated by Django 3.1.7 on 2021-04-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_indicateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateurs',
            name='libélé',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
