# Generated by Django 3.1.7 on 2021-04-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_indicateurs_libélé'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicateurs',
            old_name='libélé',
            new_name='libellé',
        ),
    ]
